version: 2
updates:
- package-ecosystem: npm
  directory: "/webapp"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.13
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
    - 17.0.4
  - dependency-name: react-intl
    versions:
    - 5.12.5
    - 5.13.0
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.15.3
    - 5.15.8
    - 5.17.0
    - 5.17.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.41
    - 15.0.0
  - dependency-name: react-redux
    versions:
    - 7.2.3
    - 7.2.4
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.8
    - 8.2.9
    - 8.3.1
    - 8.3.2
    - 8.4.0
    - 8.4.1
    - 8.4.2
  - dependency-name: redux
    versions:
    - 4.1.0
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.1
    - 5.2.4
  - dependency-name: cypress
    versions:
    - 6.6.0
    - 6.7.1
    - 7.1.0
  - dependency-name: "@formatjs/intl-relativetimeformat"
    versions:
    - 8.0.6
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
  - dependency-name: "@types/react-helmet"
    versions:
    - 6.1.1
  - dependency-name: "@wojtekmaj/enzyme-adapter-react-17"
    versions:
    - 0.6.1
  - dependency-name: intro.js
    versions:
    - 3.4.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: react-test-renderer
    versions:
    - 17.0.2
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: react-styleguidist
    versions:
    - 11.1.6
  - dependency-name: firebaseui
    versions:
    - 4.7.3
    - 4.8.0
  - dependency-name: react-detect-offline
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: react-share
    versions:
    - 4.4.0
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: react-router-transition
    versions:
    - 2.1.0
- package-ecosystem: npm
  directory: "/ranking-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
