language: node_js

node_js:
  - 14

before_script:
- cd webapp/
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- npm install

script:
  - npm run build && npm run test

deploy:
  provider: script
  script: npm run coveralls
  on:
    branch: master

after_success:
  - ./deploy.sh

env:
  global:
  - GH_REPO="marabesi/testable"
  - REACT_APP_BASE_NAME="/testable"
