version: '2'
services:
  webserver:
    image: nginx
    environment:
      - NODE_HOST=testable
      - NODE_PORT=$TESTABLE_PORT
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./docker/nginx/:/nginx
    command: /bin/bash -c "envsubst < /nginx/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
  testable:
    environment:
      - TESTABLE_PORT=$TESTABLE_PORT
    build:
      args:
        - REACT_APP_FIREBASE_JSON=$REACT_APP_FIREBASE_JSON
        - REACT_APP_RANKING_API=$REACT_APP_RANKING_API
        - REACT_APP_SURVEY_URL=$REACT_APP_SURVEY_URL
        - REACT_APP_SHOW_SURVEY=$REACT_APP_SHOW_SURVEY
        - REACT_APP_DEBUG=$REACT_APP_DEBUG
        - TESTABLE_PORT=$TESTABLE_PORT
        - PUBLIC_URL=$PUBLIC_URL
      context: ./webapp
    ports:
      - $TESTABLE_PORT:$TESTABLE_PORT
  ranking:
    environment:
      - PORT=$RANKING_PORT
      - RANKING_FIREBASE_JSON=$RANKING_FIREBASE_JSON
      - FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
      - CORS_ORIGINS=$CORS_ORIGINS
    build:
      context: ./ranking-api
    ports:
      - $RANKING_PORT:$RANKING_PORT