export default {
  HOME: '/',
  INTRO: '/intro',
  TUTORIAL_START: '/tutorial',
  TUTORIAL_END: '/tutorial-end',
  UNIT_TEST_INTRO: '/unit-testing-intro',
  UNIT_TEST: '/unit-testing',
  UNIT_TEST_END: '/unit-testing-end',
  CHALLENGE_01: '/rocket-01',
  CHALLENGE_02: '/rocket-02',
  CHALLENGE_03: '/rocket-03',
  CHALLENGE_03_01: '/rocket-03-01',
  CHALLENGE_03_02: '/rocket-03-02',
  CHALLENGE_COMPLETED_START: '/completed-intro',
  CHALLENGE_COMPLETED_END: '/completed-end',
  SURVEY: '/survey',
  TDD_START: '/tdd-intro',
  TDD: '/tdd',
};