name: Create repo visualization
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  generate_visualization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update visualization
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,*.md"